manifest:
  remotes:
    - name: blaise
      url-base: https://github.com/BlaiseRideout
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    # upstream zmk main plus zmkfirmware/zmk#1742 (caps word shift-list)
    - name: zmk
      remote: blaise
      revision: main
      import: app/west.yml
  self:
    path: corne
