#!/usr/bin/env python3
"""Generate images.c from the 128x32 art/*.png files (QMK OLED art, landscape,
drawn rotated 90 degrees like the nice!view's native orientation).

Viewed upright each piece of art is a 32x128 figure: a skull and the layer icon
(rows 0-69) above a scythe (rows 70-127). Everything is scaled a clean 2x:

- art_<name>: the skull and layer icon, for the central half. 140x64 (a 64x140
  column upright), exactly filling the area below the status strip.
- art_scythe: the scythe, which must be identical in every PNG, for the
  peripheral half. 116x64, centred in the same area.

Each image is a 140x68 1-bit LVGL image with the art centred vertically.

Usage: ./gen_images.py  (requires Pillow)
"""
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SRC_W, SRC_H = 128, 32
SCALE = 2
# Native (landscape) columns; upright row r is native column 127 - r.
SCYTHE_COLS = (0, 58)
SKULL_COLS = (58, 128)
OUT_W, OUT_H = 140, 68
STRIDE = (OUT_W + 7) // 8

HEADER = """\
/*
 * Generated by gen_images.py from the PNGs in art/ - do not edit.
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

// Palette index 0 is the background, index 1 the art.
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
#define ART_PALETTE 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
#define ART_PALETTE 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

#if LVGL_VERSION_MAJOR >= 9
#define ART_DSC(name)                                                                              \\
    const lv_image_dsc_t name = {                                                                  \\
        .header.cf = LV_COLOR_FORMAT_I1,                                                           \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#else
#define ART_DSC(name)                                                                              \\
    const lv_img_dsc_t name = {                                                                    \\
        .header.cf = LV_IMG_CF_INDEXED_1BIT,                                                       \\
        .header.always_zero = 0,                                                                   \\
        .header.reserved = 0,                                                                      \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#endif
"""


def load(path):
    src = Image.open(path).convert("1")
    assert src.size == (SRC_W, SRC_H), f"{path} must be {SRC_W}x{SRC_H}"
    return src


def render(piece):
    """Scale piece 2x and centre it in an OUT_W x OUT_H image, as packed 1-bit rows."""
    w, h = piece.width * SCALE, piece.height * SCALE
    assert w <= OUT_W and h <= OUT_H
    x0, y0 = (OUT_W - w) // 2, (OUT_H - h) // 2
    rows = []
    for y in range(OUT_H):
        row = bytearray(STRIDE)
        for x in range(OUT_W):
            sx, sy = (x - x0) // SCALE, (y - y0) // SCALE
            if 0 <= x - x0 < w and 0 <= y - y0 < h and piece.getpixel((sx, sy)):
                row[x // 8] |= 0x80 >> (x % 8)
        rows.append(row)
    return rows


def emit(name, rows):
    out = [f"\nstatic const uint8_t {name}_map[] = {{\n    ART_PALETTE\n"]
    for row in rows:
        out.append("    " + " ".join(f"0x{b:02x}," for b in row) + "\n")
    out.append(f"}};\nART_DSC({name});\n")
    return out


def main():
    out = [HEADER.replace("{w}", str(OUT_W)).replace("{h}", str(OUT_H))]
    scythe = None
    for path in sorted((HERE / "art").glob("*.png")):
        src = load(path)
        out += emit("art_" + path.stem, render(src.crop((SKULL_COLS[0], 0, SKULL_COLS[1], SRC_H))))

        piece = src.crop((SCYTHE_COLS[0], 0, SCYTHE_COLS[1], SRC_H))
        assert scythe is None or piece.tobytes() == scythe.tobytes(), f"{path}: scythe differs"
        scythe = piece
    out += emit("art_scythe", render(scythe))
    (HERE / "images.c").write_text("".join(out))


if __name__ == "__main__":
    main()
