#!/usr/bin/env python3
"""Generate images.c from the 128x32 art/*.png files (QMK OLED art, landscape,
drawn rotated 90 degrees like the nice!view's native orientation).

Viewed upright each piece of art is a 32x128 figure: a skull (rows 0-31) and the
layer icon box (rows 38-69) above a scythe (rows 75-127). Everything is scaled a
clean 2x and laid out in the 64x140 upright area below the 20px status strip:

- art_<name>: the skull and layer icon box, for the central half, with the 12px
  of spare height split evenly above, between and below them.
- art_scythe: the scythe, which must be identical in every PNG, for the
  peripheral half, centred.
- art_bt<n>_<on|off>: the scythe with the central's BLE profiles as numbered
  circles. Profile <n> is a large circle between the blade tip and the handle
  (filled when connected), drawn at the art's 1x resolution 2px (4px on screen)
  clear of the scythe. The others are a 2x2 grid centred below it, drawn at
  screen resolution with 2px lines; the grid's right column comes within 2px of
  the handle where it widens.

Each image is a 140x68 1-bit LVGL image (the upright area rotated to the
nice!view's native orientation) with the art centred across the 68px width.

Usage: ./gen_images.py  (requires Pillow)
"""
import math
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SRC_W, SRC_H = 128, 32
SCALE = 2
# Upright rows of each piece
SKULL_ROWS = (0, 32)
ICON_ROWS = (38, 70)
SCYTHE_ROWS = (75, 128)
PROFILE_COUNT = 5
# Active profile circle in 1x scythe coordinates: (centre x, centre y, diameter).
# Centred between the 2px wide part of the blade tip (columns 0-1) and the
# handle (column 27), as high as the padding allows.
ACTIVE_CIRCLE = (14.5, 21.5, 17)
ACTIVE_PADDING = 2
# Inactive profile grid in screen pixels: circle diameter and gap between them,
# centred under the active circle and the same gap below it.
INACTIVE_DIAMETER = 20
INACTIVE_GAP = 2
INACTIVE_TOP_GAP = 4
INACTIVE_PADDING = 2
DIGITS_3X5 = {
    1: ".#.##..#..#.###", 2: "##...#.#.#..###", 3: "##...#.#...###.",
    4: "#.##.####..#..#", 5: "####..##...###.",
}
DIGITS_5X9 = {
    1: "..#...##..#.#....#....#....#....#....#..#####",
    2: ".###.#...#....#....#...#...#...#...#....#####",
    3: ".###.#...#....#....#..##.....#....##...#.###.",
    4: "...#...##..#.#.#..#.#..#.#####...#....#....#.",
    5: "######....#....####.....#....#....##...#.###.",
}
# Upright art area, and the native image it is rotated into
AREA_W, AREA_H = 64, 140
OUT_W, OUT_H = AREA_H, 68
STRIDE = (OUT_W + 7) // 8

HEADER = """\
/*
 * Generated by gen_images.py from the PNGs in art/ - do not edit.
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

// Palette index 0 is the background, index 1 the art.
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
#define ART_PALETTE 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
#define ART_PALETTE 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

#if LVGL_VERSION_MAJOR >= 9
#define ART_DSC(name)                                                                              \\
    const lv_image_dsc_t name = {                                                                  \\
        .header.cf = LV_COLOR_FORMAT_I1,                                                           \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#else
#define ART_DSC(name)                                                                              \\
    const lv_img_dsc_t name = {                                                                    \\
        .header.cf = LV_IMG_CF_INDEXED_1BIT,                                                       \\
        .header.always_zero = 0,                                                                   \\
        .header.reserved = 0,                                                                      \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#endif
"""


def load(path):
    src = Image.open(path).convert("1")
    assert src.size == (SRC_W, SRC_H), f"{path} must be {SRC_W}x{SRC_H}"
    return src.rotate(90, expand=True)  # upright, 32x128


def crop(upright, rows):
    return upright.crop((0, rows[0], SRC_H, rows[1]))


def scale(p):
    return p.resize((p.width * SCALE, p.height * SCALE), Image.NEAREST)


def disc(cx, cy, d):
    r = d / 2 - 0.25  # avoids single-pixel nubs at the four extremes
    return {(x, y) for x in range(math.floor(cx - d / 2), math.ceil(cx + d / 2))
            for y in range(math.floor(cy - d / 2), math.ceil(cy + d / 2))
            if math.hypot(x + 0.5 - cx, y + 0.5 - cy) <= r}


def ring(cx, cy, d, width=1):
    return disc(cx, cy, d) - disc(cx, cy, d - 2 * width)


def digit(n, cx, cy, font, w, h, scale=1):
    """A digit centred on (cx, cy), with each font pixel drawn scale x scale."""
    x0, y0 = math.floor(cx - w * scale / 2), math.floor(cy - h * scale / 2)
    return {(x0 + (i % w) * scale + dx, y0 + (i // w) * scale + dy)
            for i, c in enumerate(font[n]) if c == "#" for dx in range(scale) for dy in range(scale)}


def ink(image):
    return {(x, y) for x in range(image.width) for y in range(image.height) if image.getpixel((x, y))}


def clearance(shapes, art):
    """Empty pixels between shapes and art (Chebyshev distance - 1)."""
    return min(max(abs(x - a), abs(y - b)) for x, y in shapes for a, b in art) - 1


def draw(image, on, off=frozenset()):
    assert all(0 <= x < image.width and 0 <= y < image.height for x, y in on)
    for xy in on - off:
        image.putpixel(xy, 1)


def profiles(scythe, active, connected):
    """The upright area with the scythe and profile circles (profiles numbered from 1)."""
    cx, cy, d = ACTIVE_CIRCLE
    num = digit(active, cx, cy, DIGITS_5X9, 5, 9)
    on, off = (disc(cx, cy, d), num) if connected else (ring(cx, cy, d) | num, set())
    assert clearance(on, ink(scythe)) >= ACTIVE_PADDING, "active profile too close to the scythe"
    p = scythe.copy()
    draw(p, on, off)

    area = stack([scale(p)])
    y0 = (AREA_H - scale(p).height) // 2  # where stack() put the scythe
    gx, size, gap = cx * SCALE, INACTIVE_DIAMETER, INACTIVE_GAP
    top = y0 + max(y for _, y in disc(cx, cy, d)) * SCALE + SCALE + INACTIVE_TOP_GAP
    left = gx - size - gap / 2
    centres = [(left + size / 2 + col * (size + gap), top + size / 2 + row * (size + gap))
               for row in (0, 1) for col in (0, 1)]
    others = [n for n in range(1, PROFILE_COUNT + 1) if n != active]
    grid = set()
    for n, (x, y) in zip(others, centres):
        grid |= ring(x, y, size, SCALE) | digit(n, x, y, DIGITS_3X5, 3, 5, SCALE)
    assert clearance(grid, ink(stack([scale(scythe)]))) >= INACTIVE_PADDING, \
        "inactive profiles too close to the scythe"
    draw(area, grid)
    return area


def stack(pieces):
    """Lay pieces out top to bottom in the upright area with equal gaps around them."""
    gap = (AREA_H - sum(p.height for p in pieces)) // (len(pieces) + 1)
    assert gap >= 0
    area = Image.new("1", (AREA_W, AREA_H))
    y = gap
    for p in pieces:
        area.paste(p, ((AREA_W - p.width) // 2, y))
        y += p.height + gap
    return area


def pack(area):
    """Rotate the upright area to native orientation, centre it, pack as 1-bit rows."""
    native = area.rotate(-90, expand=True)
    y0 = (OUT_H - native.height) // 2
    rows = []
    for y in range(OUT_H):
        row = bytearray(STRIDE)
        if 0 <= y - y0 < native.height:
            for x in range(OUT_W):
                if native.getpixel((x, y - y0)):
                    row[x // 8] |= 0x80 >> (x % 8)
        rows.append(row)
    return rows


def emit(name, rows):
    out = [f"\nstatic const uint8_t {name}_map[] = {{\n    ART_PALETTE\n"]
    for row in rows:
        out.append("    " + " ".join(f"0x{b:02x}," for b in row) + "\n")
    out.append(f"}};\nART_DSC({name});\n")
    return out


def main():
    out = [HEADER.replace("{w}", str(OUT_W)).replace("{h}", str(OUT_H))]
    scythe = None
    for path in sorted((HERE / "art").glob("*.png")):
        upright = load(path)
        out += emit("art_" + path.stem, pack(stack([scale(crop(upright, SKULL_ROWS)),
                                                     scale(crop(upright, ICON_ROWS))])))

        p = crop(upright, SCYTHE_ROWS)
        assert scythe is None or p.tobytes() == scythe.tobytes(), f"{path}: scythe differs"
        scythe = p
    out += emit("art_scythe", pack(stack([scale(scythe)])))

    for n in range(1, PROFILE_COUNT + 1):
        for state in ("off", "on"):
            out += emit(f"art_bt{n}_{state}", pack(profiles(scythe, n, state == "on")))
    out.append("\n// Indexed by [profile index][connected]\n")
    out.append(f"const lv_img_dsc_t *const art_bt_profiles[{PROFILE_COUNT}][2] = {{\n")
    for n in range(1, PROFILE_COUNT + 1):
        out.append(f"    {{&art_bt{n}_off, &art_bt{n}_on}},\n")
    out.append("};\n")
    (HERE / "images.c").write_text("".join(out))


if __name__ == "__main__":
    main()
