#!/usr/bin/env python3
"""Generate images.c from the 128x32 art/*.png files (QMK OLED art, landscape,
drawn rotated 90 degrees like the nice!view's native orientation).

Viewed upright each piece of art is a 32x128 figure: a skull (rows 0-31) and the
layer icon box (rows 38-69) above a scythe (rows 75-127). Everything is scaled a
clean 2x and laid out in the 64x140 upright area below the 20px status strip:

- art_<name>: the skull and layer icon box, for the central half, with the 12px
  of spare height split evenly above, between and below them.
- art_scythe: the scythe, which must be identical in every PNG, for the
  peripheral half, centred.

Each image is a 140x68 1-bit LVGL image (the upright area rotated to the
nice!view's native orientation) with the art centred across the 68px width.

Usage: ./gen_images.py  (requires Pillow)
"""
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SRC_W, SRC_H = 128, 32
SCALE = 2
# Upright rows of each piece
SKULL_ROWS = (0, 32)
ICON_ROWS = (38, 70)
SCYTHE_ROWS = (75, 128)
# Upright art area, and the native image it is rotated into
AREA_W, AREA_H = 64, 140
OUT_W, OUT_H = AREA_H, 68
STRIDE = (OUT_W + 7) // 8

HEADER = """\
/*
 * Generated by gen_images.py from the PNGs in art/ - do not edit.
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

// Palette index 0 is the background, index 1 the art.
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
#define ART_PALETTE 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff,
#else
#define ART_PALETTE 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff,
#endif

#if LVGL_VERSION_MAJOR >= 9
#define ART_DSC(name)                                                                              \\
    const lv_image_dsc_t name = {                                                                  \\
        .header.cf = LV_COLOR_FORMAT_I1,                                                           \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#else
#define ART_DSC(name)                                                                              \\
    const lv_img_dsc_t name = {                                                                    \\
        .header.cf = LV_IMG_CF_INDEXED_1BIT,                                                       \\
        .header.always_zero = 0,                                                                   \\
        .header.reserved = 0,                                                                      \\
        .header.w = {w},                                                                          \\
        .header.h = {h},                                                                           \\
        .data_size = sizeof(name##_map),                                                           \\
        .data = name##_map,                                                                        \\
    }
#endif
"""


def load(path):
    src = Image.open(path).convert("1")
    assert src.size == (SRC_W, SRC_H), f"{path} must be {SRC_W}x{SRC_H}"
    return src.rotate(90, expand=True)  # upright, 32x128


def piece(upright, rows):
    p = upright.crop((0, rows[0], SRC_H, rows[1]))
    return p.resize((p.width * SCALE, p.height * SCALE), Image.NEAREST)


def stack(pieces):
    """Lay pieces out top to bottom in the upright area with equal gaps around them."""
    gap = (AREA_H - sum(p.height for p in pieces)) // (len(pieces) + 1)
    assert gap >= 0
    area = Image.new("1", (AREA_W, AREA_H))
    y = gap
    for p in pieces:
        area.paste(p, ((AREA_W - p.width) // 2, y))
        y += p.height + gap
    return area


def pack(area):
    """Rotate the upright area to native orientation, centre it, pack as 1-bit rows."""
    native = area.rotate(-90, expand=True)
    y0 = (OUT_H - native.height) // 2
    rows = []
    for y in range(OUT_H):
        row = bytearray(STRIDE)
        if 0 <= y - y0 < native.height:
            for x in range(OUT_W):
                if native.getpixel((x, y - y0)):
                    row[x // 8] |= 0x80 >> (x % 8)
        rows.append(row)
    return rows


def emit(name, rows):
    out = [f"\nstatic const uint8_t {name}_map[] = {{\n    ART_PALETTE\n"]
    for row in rows:
        out.append("    " + " ".join(f"0x{b:02x}," for b in row) + "\n")
    out.append(f"}};\nART_DSC({name});\n")
    return out


def main():
    out = [HEADER.replace("{w}", str(OUT_W)).replace("{h}", str(OUT_H))]
    scythe = None
    for path in sorted((HERE / "art").glob("*.png")):
        upright = load(path)
        out += emit("art_" + path.stem, pack(stack([piece(upright, SKULL_ROWS),
                                                     piece(upright, ICON_ROWS)])))

        p = piece(upright, SCYTHE_ROWS)
        assert scythe is None or p.tobytes() == scythe.tobytes(), f"{path}: scythe differs"
        scythe = p
    out += emit("art_scythe", pack(stack([scythe])))
    (HERE / "images.c").write_text("".join(out))


if __name__ == "__main__":
    main()
